### ISSUE TITLE
Logic errors in intersection

### ISSUE THREAD

**Issue by FergusYip** [saberscientist/compare-string#5]
The intersection function does not check if `first` is a set. Hence if `first` contains duplicate values it would lead to incorrect results.

```js
const intersections = (first, second) => {
    const value = [];
    const __first = first.slice()
    const __second = second.slice()

    while (__first.length) {
        const x = __first.shift()
        if (__second.includes(x)) value.push(x)
    }
    return value.length;
};
```

**Comment by saberscientist** [comment]
While this is a valid issue, you've seemed to fix it yourself in #6 (and even address it as so), where you use create a function that uses the `Set` constructor to remove duplicate values from the original `first` array.
